### ISSUE TITLE
Need resource tony_peds

### ISSUE THREAD

**Issue by ALENTL** [tony-stark-17/ts-lockers#3]
exports["tony_peds"]:NewPed
Line 68 in ts-lockers/main.lua
Please make the tony_peds resource open source. 
Also I found 
![image](https://user-images.githubusercontent.com/82425585/171998186-65d419a1-5bba-43ad-9d75-e85b3a185cc3.png)
resource fivem-target also. Just grabbed it from github
Please add the dependency link in readme.
Thanks in advance

**Comment by ALENTL** [comment]
@tony-stark-17 Please look forward into the issue. Thanks

**Comment by tony-stark-17** [comment]
https://github.com/tony-stark-17/tony_peds
